# Generated by Django 3.0.7 on 2020-07-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_rover', '0003_shared_collection_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_collection',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
