# Generated by Django 3.0.7 on 2020-07-12 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mars_rover', '0004_shared_collection_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_collection',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
